<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FacultySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('faculties')->insert([
            ['id'                  => '1',
             'name'                => 'Fakulta dramatických umení',
             'name_en'             => '',
             'university_id'       => '1',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '2',
             'name'                => 'Fakulta múzických umení',
             'name_en'             => '',
             'university_id'       => '1',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '3',
             'name'                => 'Fakulta výtvarných umení',
             'name_en'             => '',
             'university_id'       => '1',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '4',
             'name'                => 'Divadelní fakulta',
             'name_en'             => '',
             'university_id'       => '2',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '5',
             'name'                => 'Filmová a televizní fakulta',
             'name_en'             => '',
             'university_id'       => '2',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '6',
             'name'                => 'Hudební a taneční fakulta',
             'name_en'             => '',
             'university_id'       => '2',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '7',
             'name'                => 'Fakulta agrobiologie potravinových a přírodních zdrojů',
             'name_en'             => 'Faculty of Agrobiology, Food and Natural Resources',
             'university_id'       => '3',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '8',
             'name'                => 'Fakulta lesnická a dřevařská',
             'name_en'             => '',
             'university_id'       => '3',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '9',
             'name'                => 'Fakulta životního prostředí',
             'name_en'             => '',
             'university_id'       => '3',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '10',
             'name'                => 'Provozně ekonomická fakulta',
             'name_en'             => '',
             'university_id'       => '3',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '11',
             'name'                => 'Technická fakulta',
             'name_en'             => '',
             'university_id'       => '3',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '12',
             'name'                => 'Fakulta architektury',
             'name_en'             => '',
             'university_id'       => '4',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '13',
             'name'                => 'Fakulta biomedicínského inženýrství',
             'name_en'             => '',
             'university_id'       => '4',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '14',
             'name'                => 'Fakulta dopravní',
             'name_en'             => '',
             'university_id'       => '4',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '15',
             'name'                => 'Fakulta elektrotechnická',
             'name_en'             => 'Faculty of Electrical Engineering',
             'university_id'       => '4',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '16',
             'name'                => 'Fakulta informačních technologií',
             'name_en'             => '',
             'university_id'       => '4',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '17',
             'name'                => 'Fakulta jaderná a fyzikálně inženýrská',
             'name_en'             => '',
             'university_id'       => '4',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '18',
             'name'                => 'Fakulta stavební',
             'name_en'             => '',
             'university_id'       => '4',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '19',
             'name'                => 'Fakulta strojní',
             'name_en'             => '',
             'university_id'       => '4',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '20',
             'name'                => 'Fakulta aplikovaných jazykov',
             'name_en'             => '',
             'university_id'       => '5',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '21',
             'name'                => 'Fakulta hospodárskej informatiky',
             'name_en'             => '',
             'university_id'       => '5',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '22',
             'name'                => 'Fakulta medzinárodných vzťahov',
             'name_en'             => '',
             'university_id'       => '5',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '23',
             'name'                => 'Fakulta podnikového manažmentu',
             'name_en'             => '',
             'university_id'       => '5',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '24',
             'name'                => 'Národohospodárska fakulta',
             'name_en'             => '',
             'university_id'       => '5',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '25',
             'name'                => 'Obchodná fakulta Ekonomickej univerzity v Bratislave',
             'name_en'             => '',
             'university_id'       => '5',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '26',
             'name'                => 'Podnikovohospodárska fakulta, Košice',
             'name_en'             => '',
             'university_id'       => '5',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '27',
             'name'                => 'Divadelní fakulta',
             'name_en'             => '',
             'university_id'       => '6',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '28',
             'name'                => 'Hudební fakulta',
             'name_en'             => '',
             'university_id'       => '6',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '29',
             'name'                => 'Ekonomická fakulta',
             'name_en'             => '',
             'university_id'       => '7',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '30',
             'name'                => 'Fakulta rybářství a ochrany vod',
             'name_en'             => '',
             'university_id'       => '7',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '31',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '7',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '32',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '7',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '33',
             'name'                => 'Přírodovědecká fakulta',
             'name_en'             => '',
             'university_id'       => '7',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '34',
             'name'                => 'Teologická fakulta',
             'name_en'             => '',
             'university_id'       => '7',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '35',
             'name'                => 'Ústav fyzikální biologie',
             'name_en'             => '',
             'university_id'       => '7',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '36',
             'name'                => 'Zdravotně sociální fakulta',
             'name_en'             => '',
             'university_id'       => '7',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '37',
             'name'                => 'Zemědělská fakulta',
             'name_en'             => '',
             'university_id'       => '7',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '38',
             'name'                => 'Fakulta zdravotníctva',
             'name_en'             => '',
             'university_id'       => '8',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '39',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '8',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '40',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '8',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '41',
             'name'                => 'Teologická fakulta',
             'name_en'             => '',
             'university_id'       => '8',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '42',
             'name'                => 'Fakulta ekonomicko-správní',
             'name_en'             => '',
             'university_id'       => '9',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '43',
             'name'                => 'Fakulta informatiky',
             'name_en'             => '',
             'university_id'       => '9',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '44',
             'name'                => 'Fakulta sociálních studií',
             'name_en'             => '',
             'university_id'       => '9',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '45',
             'name'                => 'Fakulta sportovních studií',
             'name_en'             => '',
             'university_id'       => '9',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '46',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '9',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '47',
             'name'                => 'Lékařská fakulta',
             'name_en'             => '',
             'university_id'       => '9',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '48',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '9',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '49',
             'name'                => 'Právnická fakulta',
             'name_en'             => '',
             'university_id'       => '9',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '50',
             'name'                => 'Přírodovědecká fakulta',
             'name_en'             => 'Faculty of Science',
             'university_id'       => '9',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '51',
             'name'                => 'Agronomická fakulta',
             'name_en'             => '',
             'university_id'       => '10',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '52',
             'name'                => 'Fakulta regionálního rozvoje a mezinárodních studií',
             'name_en'             => '',
             'university_id'       => '10',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '53',
             'name'                => 'Lesnická a dřevařská fakulta',
             'name_en'             => '',
             'university_id'       => '10',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '54',
             'name'                => 'Provozně ekonomická fakulta',
             'name_en'             => '',
             'university_id'       => '10',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '55',
             'name'                => 'Zahradnická fakulta',
             'name_en'             => '',
             'university_id'       => '10',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '56',
             'name'                => 'Fakulta sociálních studií',
             'name_en'             => '',
             'university_id'       => '11',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '57',
             'name'                => 'Fakulta umění',
             'name_en'             => '',
             'university_id'       => '11',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '58',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '11',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '59',
             'name'                => 'Lékařská fakulta',
             'name_en'             => '',
             'university_id'       => '11',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '60',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '11',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '61',
             'name'                => 'Přírodovědecká fakulta',
             'name_en'             => '',
             'university_id'       => '11',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '62',
             'name'                => 'Fakulta humanitných a prírodných vied',
             'name_en'             => '',
             'university_id'       => '12',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '63',
             'name'                => 'Fakulta manažmentu',
             'name_en'             => '',
             'university_id'       => '12',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '64',
             'name'                => 'Fakulta športu',
             'name_en'             => '',
             'university_id'       => '12',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '65',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '12',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '66',
             'name'                => 'Gréckokatolícka teologická fakulta',
             'name_en'             => '',
             'university_id'       => '12',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '67',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '12',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '68',
             'name'                => 'Pravoslávna bohoslovecká fakulta Prešovskej univerzity v Prešove',
             'name_en'             => '',
             'university_id'       => '12',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '69',
             'name'                => 'Fakulta veřejných politik v Opavě',
             'name_en'             => '',
             'university_id'       => '13',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '70',
             'name'                => 'Filozoficko-přírodovědecká fakulta v Opavě',
             'name_en'             => '',
             'university_id'       => '13',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '71',
             'name'                => 'Obchodně podnikatelská fakulta v Karviné',
             'name_en'             => '',
             'university_id'       => '13',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '72',
             'name'                => 'Fakulta agrobiológie a potravinových zdrojov',
             'name_en'             => '',
             'university_id'       => '14',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '73',
             'name'                => 'Fakulta biotechnológie a potravinárstva',
             'name_en'             => 'Faculty of Biotechnology and Food Sciences',
             'university_id'       => '14',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '74',
             'name'                => 'Fakulta ekonomiky a manažmentu',
             'name_en'             => '',
             'university_id'       => '14',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '75',
             'name'                => 'Fakulta európskych štúdií a regionálneho rozvoja',
             'name_en'             => '',
             'university_id'       => '14',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '76',
             'name'                => 'Fakulta záhradníctva a krajinného inžinierstva',
             'name_en'             => '',
             'university_id'       => '14',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '77',
             'name'                => 'Technická fakulta',
             'name_en'             => '',
             'university_id'       => '14',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '78',
             'name'                => 'Fakulta architektúry STU v Bratislave',
             'name_en'             => '',
             'university_id'       => '15',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '79',
             'name'                => 'Fakulta chemickej a potravinárskej technológie',
             'name_en'             => 'Faculty of Chemical and Food Technology',
             'university_id'       => '15',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '80',
             'name'                => 'Fakulta elektrotechniky a informatiky',
             'name_en'             => '',
             'university_id'       => '15',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '81',
             'name'                => 'Fakulta informatiky a informačných technológií',
             'name_en'             => '',
             'university_id'       => '15',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '82',
             'name'                => 'Materiálovotechnologická fakulta, Trnava',
             'name_en'             => '',
             'university_id'       => '15',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '83',
             'name'                => 'Stavebná fakulta',
             'name_en'             => 'Faculty of Civil Engineering',
             'university_id'       => '15',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '84',
             'name'                => 'Strojnícka fakulta',
             'name_en'             => '',
             'university_id'       => '15',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '85',
             'name'                => 'Fakulta ošetrovateľstva a zdravotníckych odborných štúdií',
             'name_en'             => '',
             'university_id'       => '16',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '86',
             'name'                => 'Fakulta verejného zdravotníctva',
             'name_en'             => '',
             'university_id'       => '16',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '87',
             'name'                => 'Fakulta zdravotníctva',
             'name_en'             => '',
             'university_id'       => '16',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '88',
             'name'                => 'Lekárska fakulta',
             'name_en'             => '',
             'university_id'       => '16',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '89',
             'name'                => 'Ekonomická fakulta',
             'name_en'             => '',
             'university_id'       => '17',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '90',
             'name'                => 'Fakulta baníctva, ekológie, riadenia a geotechnológií',
             'name_en'             => '',
             'university_id'       => '17',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '91',
             'name'                => 'Fakulta elektrotechniky a informatiky',
             'name_en'             => '',
             'university_id'       => '17',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '92',
             'name'                => 'Fakulta umení',
             'name_en'             => '',
             'university_id'       => '17',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '93',
             'name'                => 'Fakulta výrobných technológií',
             'name_en'             => '',
             'university_id'       => '17',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '94',
             'name'                => 'Hutnícka fakulta',
             'name_en'             => '',
             'university_id'       => '17',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '95',
             'name'                => 'Letecká fakulta',
             'name_en'             => '',
             'university_id'       => '17',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '96',
             'name'                => 'Stavebná fakulta',
             'name_en'             => '',
             'university_id'       => '17',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '97',
             'name'                => 'Strojnícka fakulta',
             'name_en'             => '',
             'university_id'       => '17',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '98',
             'name'                => 'Ekonomická fakulta',
             'name_en'             => '',
             'university_id'       => '18',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '99',
             'name'                => 'Fakulta mechatroniky, informatiky a mezioborových studií',
             'name_en'             => '',
             'university_id'       => '18',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '100',
             'name'                => 'Fakulta přírodovědně-humanitní a pedagogická',
             'name_en'             => '',
             'university_id'       => '18',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '101',
             'name'                => 'Fakulta strojní',
             'name_en'             => '',
             'university_id'       => '18',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '102',
             'name'                => 'Fakulta textilní',
             'name_en'             => '',
             'university_id'       => '18',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '103',
             'name'                => 'Fakulta umění a architektury',
             'name_en'             => '',
             'university_id'       => '18',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '104',
             'name'                => 'Drevárska fakulta',
             'name_en'             => '',
             'university_id'       => '19',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '105',
             'name'                => 'Fakulta ekológie a environmentalistiky',
             'name_en'             => '',
             'university_id'       => '19',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '106',
             'name'                => 'Fakulta environmentálnej a výrobnej techniky',
             'name_en'             => '',
             'university_id'       => '19',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '107',
             'name'                => 'Lesnícka fakulta',
             'name_en'             => '',
             'university_id'       => '19',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '108',
             'name'                => 'Technická univerzita vo Zvolene',
             'name_en'             => '',
             'university_id'       => '19',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '109',
             'name'                => 'Fakulta mechatroniky',
             'name_en'             => '',
             'university_id'       => '20',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '110',
             'name'                => 'Fakulta priemyselných technológií',
             'name_en'             => '',
             'university_id'       => '20',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '111',
             'name'                => 'Fakulta sociálno-ekonomických vzťahov',
             'name_en'             => '',
             'university_id'       => '20',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '112',
             'name'                => 'Fakulta špeciálnej techniky',
             'name_en'             => '',
             'university_id'       => '20',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '113',
             'name'                => 'Fakulta zdravotníctva',
             'name_en'             => '',
             'university_id'       => '20',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '114',
             'name'                => 'Fakulta zdravotníctva a sociálnej práce',
             'name_en'             => '',
             'university_id'       => '21',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '115',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '21',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '116',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => 'Faculty of Education',
             'university_id'       => '21',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '117',
             'name'                => 'Právnická fakulta',
             'name_en'             => '',
             'university_id'       => '21',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '118',
             'name'                => 'Teologická fakulta, Bratislava',
             'name_en'             => '',
             'university_id'       => '21',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '119',
             'name'                => 'Fakulta informatiky a managementu',
             'name_en'             => '',
             'university_id'       => '22',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '120',
             'name'                => 'Fakulta mechatroniky, informatiky a mezioborových studií',
             'name_en'             => '',
             'university_id'       => '22',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '121',
             'name'                => 'Fakulta umění a architektury',
             'name_en'             => '',
             'university_id'       => '22',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '122',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '22',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '123',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '22',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '124',
             'name'                => 'Přírodovědecká fakulta',
             'name_en'             => '',
             'university_id'       => '22',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '125',
             'name'                => 'Ekonomická fakulta',
             'name_en'             => '',
             'university_id'       => '23',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '126',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '23',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '127',
             'name'                => 'Reformovaná teologická fakulta',
             'name_en'             => '',
             'university_id'       => '23',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '128',
             'name'                => 'Fakulta sociálně ekonomická',
             'name_en'             => '',
             'university_id'       => '24',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '129',
             'name'                => 'Fakulta umění a designu',
             'name_en'             => '',
             'university_id'       => '24',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '130',
             'name'                => 'Fakulta výrobních technologií a managementu',
             'name_en'             => '',
             'university_id'       => '24',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '131',
             'name'                => 'Fakulta životního prostředí',
             'name_en'             => '',
             'university_id'       => '24',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '132',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '24',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '133',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '24',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '134',
             'name'                => 'Přírodovědecká fakult',
             'name_en'             => '',
             'university_id'       => '24',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '135',
             'name'                => '1. lekárska fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '136',
             'name'                => '2. lekárska fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '137',
             'name'                => '3. lekárska fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '138',
             'name'                => 'Evanjelická teologická fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '139',
             'name'                => 'Fakulta humanitných štúdi',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '140',
             'name'                => 'Fakulta sociálnych vied',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '141',
             'name'                => 'Fakulta telesnej výchovy a športu',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '142',
             'name'                => 'Farmaceutická fakulta v Hradci Králové',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '143',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '144',
             'name'                => 'Husitská teologická fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '145',
             'name'                => 'Katolícká teologická fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '146',
             'name'                => 'Lekárska fakulta v Hradci Králové',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '147',
             'name'                => 'Lekárska fakulta v Plzni',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '148',
             'name'                => 'Matematicko-fyzikálna fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '149',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '150',
             'name'                => 'Právnicka fakulta',
             'name_en'             => '',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '151',
             'name'                => 'Prírodovedecká fakulta',
             'name_en'             => 'Faculty of Science',
             'university_id'       => '25',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '152',
             'name'                => 'Evanjelická bohoslovecká fakulta',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '153',
             'name'                => 'Fakulta managementu',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '154',
             'name'                => 'Fakulta matematiky, fyziky a informatiky',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '155',
             'name'                => 'Fakulta sociálnych a ekonomických vied',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '156',
             'name'                => 'Fakulta telesnej výchovy a športu',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '157',
             'name'                => 'Farmaceutická fakulta',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '158',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '159',
             'name'                => 'Jesseniova lekárska fakulta',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '160',
             'name'                => 'Lekárska fakulta',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '161',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '162',
             'name'                => 'Právnická fakulta',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '163',
             'name'                => 'Prírodovedecká fakulta',
             'name_en'             => 'Faculty of Natural Sciences',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '164',
             'name'                => 'Rímskokatolícka cyrilometodská bohoslovecká fakulta',
             'name_en'             => '',
             'university_id'       => '26',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '165',
             'name'                => 'Fakulta prírodných vied',
             'name_en'             => '',
             'university_id'       => '27',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '166',
             'name'                => 'Fakulta sociálnych vied a zdravotníctva',
             'name_en'             => '',
             'university_id'       => '27',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '167',
             'name'                => 'Fakulta stredoeurópskych štúdií',
             'name_en'             => '',
             'university_id'       => '27',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '168',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '27',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '169',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '27',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '170',
             'name'                => 'Ekonomická fakulta',
             'name_en'             => '',
             'university_id'       => '28',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '171',
             'name'                => 'Fakulta humanitných vied Univerzity Mateja Bela v Banskej Bystrici',
             'name_en'             => '',
             'university_id'       => '28',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '172',
             'name'                => 'Fakulta politických vied a medzinárodných vzťahov',
             'name_en'             => '',
             'university_id'       => '28',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '173',
             'name'                => 'Fakulta prírodných vied',
             'name_en'             => '',
             'university_id'       => '28',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '174',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '28',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '175',
             'name'                => 'Právnická fakulta',
             'name_en'             => '',
             'university_id'       => '28',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '176',
             'name'                => 'Cyrilometodějská teologická fakulta',
             'name_en'             => '',
             'university_id'       => '29',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '177',
             'name'                => 'Fakulta tělesné kultury',
             'name_en'             => '',
             'university_id'       => '29',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '178',
             'name'                => 'Fakulta zdravotnických věd',
             'name_en'             => '',
             'university_id'       => '29',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '179',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '29',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '180',
             'name'                => 'Lékařská fakulta',
             'name_en'             => '',
             'university_id'       => '29',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '181',
             'name'                => 'Pedagogická fakulta',
             'name_en'             => '',
             'university_id'       => '29',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '182',
             'name'                => 'Právnická fakulta',
             'name_en'             => '',
             'university_id'       => '29',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '183',
             'name'                => 'Přírodovědecká fakulta',
             'name_en'             => 'Faculty of Science',
             'university_id'       => '29',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '184',
             'name'                => 'Dopravní fakulta Jana Pernera',
             'name_en'             => '',
             'university_id'       => '30',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '185',
             'name'                => 'Fakulta chemicko-technologická',
             'name_en'             => 'Faculty of Chemical Technology',
             'university_id'       => '30',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '186',
             'name'                => 'Fakulta ekonomicko-správní',
             'name_en'             => '',
             'university_id'       => '30',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '187',
             'name'                => 'Fakulta elektrotechniky a informatiky',
             'name_en'             => '',
             'university_id'       => '30',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '188',
             'name'                => 'Fakulta filozofická',
             'name_en'             => '',
             'university_id'       => '30',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '189',
             'name'                => 'Fakulta restaurování',
             'name_en'             => '',
             'university_id'       => '30',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '190',
             'name'                => 'Fakulta zdravotnických studií',
             'name_en'             => '',
             'university_id'       => '30',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '191',
             'name'                => 'Fakulta verejnej správy',
             'name_en'             => '',
             'university_id'       => '31',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '192',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '31',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '193',
             'name'                => 'Lekárska fakulta',
             'name_en'             => '',
             'university_id'       => '31',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '194',
             'name'                => 'Právnická fakulta',
             'name_en'             => '',
             'university_id'       => '31',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '195',
             'name'                => 'Prírodovedecká fakulta',
             'name_en'             => 'Faculty of Science',
             'university_id'       => '31',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '196',
             'name'                => 'Fakulta masmediálnej komunikácie',
             'name_en'             => '',
             'university_id'       => '32',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '197',
             'name'                => 'Fakulta prírodných vied',
             'name_en'             => 'Faculty of Natural Sciences',
             'university_id'       => '32',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '198',
             'name'                => 'Filozofická fakulta',
             'name_en'             => '',
             'university_id'       => '32',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '199',
             'name'                => 'Fakulta aplikované informatiky',
             'name_en'             => '',
             'university_id'       => '33',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '200',
             'name'                => 'Fakulta humanitních studií',
             'name_en'             => '',
             'university_id'       => '33',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '201',
             'name'                => 'Fakulta logistiky a krizového řízení',
             'name_en'             => '',
             'university_id'       => '33',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '202',
             'name'                => 'Fakulta managementu a ekonomiky',
             'name_en'             => '',
             'university_id'       => '33',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '203',
             'name'                => 'Fakulta multimediálních komunikací',
             'name_en'             => '',
             'university_id'       => '33',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '204',
             'name'                => 'Fakulta technologická',
             'name_en'             => '',
             'university_id'       => '33',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '205',
             'name'                => 'Elektrotechnická fakulta',
             'name_en'             => '',
             'university_id'       => '34',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '206',
             'name'                => 'Fakulta humanitných vied',
             'name_en'             => '',
             'university_id'       => '34',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '207',
             'name'                => 'Fakulta prevádzky a ekonomiky dopravy a spojov',
             'name_en'             => '',
             'university_id'       => '34',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '208',
             'name'                => 'Fakulta riadenia a informatiky',
             'name_en'             => '',
             'university_id'       => '34',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '209',
             'name'                => 'Fakulta špeciálneho inžinierstva',
             'name_en'             => '',
             'university_id'       => '34',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '210',
             'name'                => 'Stavebná fakulta',
             'name_en'             => '',
             'university_id'       => '34',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '211',
             'name'                => 'Strojnícka fakulta',
             'name_en'             => '',
             'university_id'       => '34',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '212',
             'name'                => 'Fakulta chemické technologie',
             'name_en'             => 'Faculty of Chemical Technology',
             'university_id'       => '35',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '213',
             'name'                => 'Fakulta technologie ochrany prostředí',
             'name_en'             => '',
             'university_id'       => '35',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '214',
             'name'                => 'Fakulta potravinářské a biochemické technologie',
             'name_en'             => 'Faculty of Food and Biochemical Technology',
             'university_id'       => '35',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '215',
             'name'                => 'Fakulta chemicko-inženýrská',
             'name_en'             => '',
             'university_id'       => '35',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '216',
             'name'                => 'Fakulta stavební',
             'name_en'             => '',
             'university_id'       => '36',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '217',
             'name'                => 'Fakulta strojního inženýrství',
             'name_en'             => '',
             'university_id'       => '36',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '218',
             'name'                => 'Fakulta elektrotechniky a komunikačních technologií',
             'name_en'             => '',
             'university_id'       => '36',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '219',
             'name'                => 'Fakulta architektury',
             'name_en'             => '',
             'university_id'       => '36',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '220',
             'name'                => 'Fakulta chemická',
             'name_en'             => 'Faculty of Chemistry',
             'university_id'       => '36',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '221',
             'name'                => 'Fakulta podnikatelská',
             'name_en'             => '',
             'university_id'       => '36',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '222',
             'name'                => 'Fakulta výtvarných umění',
             'name_en'             => '',
             'university_id'       => '36',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '223',
             'name'                => 'Fakulta informačních technologií',
             'name_en'             => '',
             'university_id'       => '36',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '224',
             'name'                => 'Hornicko-geologická fakulta',
             'name_en'             => 'Faculty of Mining and Geology',
             'university_id'       => '37',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '225',
             'name'                => 'Fakulta materiálově-technologická',
             'name_en'             => 'Faculty of Materials Science and Technology',
             'university_id'       => '37',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '226',
             'name'                => 'Fakulta strojní',
             'name_en'             => 'Faculty of Mechanical Engineering',
             'university_id'       => '37',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '227',
             'name'                => 'Ekonomická fakulta',
             'name_en'             => 'Faculty of Economics',
             'university_id'       => '37',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '228',
             'name'                => 'Fakulta elektrotechniky a informatiky',
             'name_en'             => 'Faculty of Electrical Engineering and Computer Science',
             'university_id'       => '37',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '229',
             'name'                => 'Fakulta stavební',
             'name_en'             => 'Faculty of Civil Engineering',
             'university_id'       => '37',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '230',
             'name'                => 'Fakulta bezpečnostního inženýrství',
             'name_en'             => 'Faculty of Safety Engineering',
             'university_id'       => '37',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '231',
             'name'                => 'Fakulta automatického riadenia, elektroniky a informatiky',
             'name_en'             => 'Faculty of Automatic Control, Electronics and Computer Science',
             'university_id'       => '38',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '232',
             'name'                => 'Ústav hygieny a technológie mlieka',
             'name_en'             => 'Institute of Milk Hygiene and Technology',
             'university_id'       => '39',
             'created_at'          => now(),
             'updated_at'          => now()]
        ]);
    }
}
