<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegistrationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('registrations')->insert([
        [
            'id'                  => '1',
            'conf_id'             => '2',
            'user_id'             => '11',
            'name_contribution'   => 'Meranie pH',
            'abstract_original_file' => 'Míková_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '1',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],

        [
            'id'                  => '2',
            'conf_id'             => '2',
            'user_id'             => '9',
            'name_contribution'   => 'Včelia farma',
            'abstract_original_file' => 'Gonda_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '33',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK0900000000007899878',
            'swift'               => 'TATRSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],

        [
            'id'                  => '3',
            'conf_id'             => '2',
            'user_id'             => '10',
            'name_contribution'   => 'Neurónové siete v medicíne',
            'abstract_original_file' => 'Varmeďová_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '1',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'GIBASKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],
            
        // //////////////////////////////////////////////////////

        [
            'id'                  => '4',
            'conf_id'             => '2',
            'user_id'             => '12',
            'name_contribution'   => 'Sledovanie teplôt plošne skladovaných zrnín - experiment',
            'abstract_original_file' => 'Fáber_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],
        [
            'id'                  => '5',
            'conf_id'             => '2',
            'user_id'             => '13',
            'name_contribution'   => 'Identifikácia a riadenie kogeneračnej jednotky',
            'abstract_original_file' => 'Homolová_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],
        [
            'id'                  => '6',
            'conf_id'             => '2',
            'user_id'             => '14',
            'name_contribution'   => 'Explicitné prediktívne riadenie systému s rýchlou dynamikou',
            'abstract_original_file' => 'Krištof_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],
        [
            'id'                  => '7',
            'conf_id'             => '2',
            'user_id'             => '15',
            'name_contribution'   => 'Automatizácia v pestovaní rastlín',
            'abstract_original_file' => 'Nguyen_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],
        [
            'id'                  => '8',
            'conf_id'             => '2',
            'user_id'             => '16',
            'name_contribution'   => 'Návrh prediktívneho riadenia pre procesy chemického priemyslu',
            'abstract_original_file' => 'Pavlovičová_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],
        [
            'id'                  => '9',
            'conf_id'             => '2',
            'user_id'             => '17',
            'name_contribution'   => 'Ladenie MPC regulátora',
            'abstract_original_file' => 'Puk_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],
        [
            'id'                  => '10',
            'conf_id'             => '2',
            'user_id'             => '18',
            'name_contribution'   => 'Tvorba dynamických webových stránok v PHP Frameworku Laravel',
            'abstract_original_file' => 'Vogl_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],
        [
            'id'                  => '11',
            'conf_id'             => '2',
            'user_id'             => '19',
            'name_contribution'   => 'Návrh a optimalizácia klasifikačného algoritmu na identifikáciu malých molekúl použitím anotovaných spektrálnych stromov',
            'abstract_original_file' => 'Wadinger_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ],
        [
            'id'                  => '12',
            'conf_id'             => '2',
            'user_id'             => '20',
            'name_contribution'   => 'Fuzzy riadenie',
            'abstract_original_file' => 'Žabková_2022-04-07.pdf',
            'abstract_storage_file'  => 'Míková_2022-04-07.pdf',
            'phd'                 => '0',
            'section_start_id'    => '46',
            'section_final_id'    => null,
            'program_order'       => null,
            'review'              => '1',
            'iban'                => 'SK090 0000 0000 0789 9878',
            'swift'               => 'CEKOSKBX',
            'agree_bank_account'  => '1',
            'agree_gdpr'          => '1',
            'agree_citation'      => '1',
            'agree_video'         => '1',
            'award_id'            => null,
            'placement'           => null
        ]
        ]);
    }
}
