<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('universities')->insert([
            ['id'                  => '1',
             'name'                => 'Akadémia umení v Banskej Bystrici',
             'name_en'             => '',
             'shortcut'            => 'AKU',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '2',
             'name'                => 'Akademie múzických umění v Praze',
             'name_en'             => '',
             'shortcut'            => 'AMU',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '3',
             'name'                => 'Česká zemědělská univerzita v Praze',
             'name_en'             => 'Czech University of Life Sciences Prague',
             'shortcut'            => 'ČZU',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '4',
             'name'                => 'České vysoké učení technické v Praze',
             'name_en'             => 'Czech Technical University in Prague',
             'shortcut'            => 'ČVUT',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '5',
             'name'                => 'Ekonomická univerzita v Bratislave',
             'name_en'             => '',
             'shortcut'            => 'EUBA',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '6',
             'name'                => 'Janáčkova akademie múzických umění v Brně',
             'name_en'             => '',
             'shortcut'            => 'JAMU',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '7',
             'name'                => 'Jihočeská univerzita v Českých Budějovicích',
             'name_en'             => '',
             'shortcut'            => 'JU',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '8',
             'name'                => 'Katolícka univerzita v Ružomberku',
             'name_en'             => '',
             'shortcut'            => 'KU',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '9',
             'name'                => 'Masarykova univerzita v Brně',
             'name_en'             => 'Masaryk University',
             'shortcut'            => 'MUNI',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '10',
             'name'                => 'Mendelova zemědělská a lesnická universita v Brně',
             'name_en'             => '',
             'shortcut'            => 'MENDELU',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '11',
             'name'                => 'Ostravská univerzita v Ostravě',
             'name_en'             => '',
             'shortcut'            => 'OU',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '12',
             'name'                => 'Prešovská univerzita v Prešove',
             'name_en'             => '',
             'shortcut'            => 'PU',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '13',
             'name'                => 'Slezská univerzita v Opavě',
             'name_en'             => '',
             'shortcut'            => 'SU',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '14',
             'name'                => 'Poľnohospodárska univerzita v Nitre',
             'name_en'             => 'University of Agriculture in Nitra',
             'shortcut'            => 'SPU',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '15',
             'name'                => 'SLovenská Technická univerzita v Bratislave',
             'name_en'             => 'University of Technology in Bratislava',
             'shortcut'            => 'STU',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '16',
             'name'                => 'Slovenská zdravotnícka univerzita v Bratislave',
             'name_en'             => '',
             'shortcut'            => 'SZU',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '17',
             'name'                => 'Technická univerzita v Košiciach',
             'name_en'             => '',
             'shortcut'            => 'TUKE',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '18',
             'name'                => 'Technická univerzita v Liberci',
             'name_en'             => '',
             'shortcut'            => 'TUL',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '19',
             'name'                => 'Technická univerzita vo Zvolene',
             'name_en'             => '',
             'shortcut'            => 'TUZVO',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '20',
             'name'                => 'Trenčianska univerzita Alexandra Dubčeka v Trenčíne',
             'name_en'             => '',
             'shortcut'            => 'TnUAD',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '21',
             'name'                => 'Trnavská univerzita v Trnave',
             'name_en'             => 'Trnava University in Trnava',
             'shortcut'            => 'TRUNI',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '22',
             'name'                => 'Univerzita Hradec Králové',
             'name_en'             => '',
             'shortcut'            => 'UHK',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '23',
             'name'                => 'Univerzita J. Selyeho v Komárne',
             'name_en'             => '',
             'shortcut'            => 'UJS',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '24',
             'name'                => 'Univerzita Jana Evangelisty Purkyně v Ústí nad Labem',
             'name_en'             => '',
             'shortcut'            => 'UJEP',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '25',
             'name'                => 'Univerzita Karlova v Praze',
             'name_en'             => 'Charles University',
             'shortcut'            => 'UK',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '26',
             'name'                => 'Univerzita Komenského v Bratislave',
             'name_en'             => 'Comenius University in Bratislava',
             'shortcut'            => 'UK',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '27',
             'name'                => 'Univerzita Konštantína Filozofa v Nitre',
             'name_en'             => '',
             'shortcut'            => 'UKF',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '28',
             'name'                => 'Univerzita Mateja Bela v Banskej Bystrici',
             'name_en'             => '',
             'shortcut'            => 'UMB',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '29',
             'name'                => 'Univerzita Palackého v Olomouci',
             'name_en'             => 'Palacký University Olomouc',
             'shortcut'            => 'UPOL',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '30',
             'name'                => 'Univerzita Pardubice',
             'name_en'             => 'University of Pardubice',
             'shortcut'            => 'UPA',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '31',
             'name'                => 'Univerzita Pavla Jozefa Šafárika v Košiciach',
             'name_en'             => 'Pavol Jozef Šafárik University in Košice',
             'shortcut'            => 'UPJŠ',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '32',
             'name'                => 'Univerzita sv. Cyrila a Metoda v Trnave',
             'name_en'             => 'University of Ss. Cyril and Methodius in Trnava',
             'shortcut'            => 'UCM',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '33',
             'name'                => 'Univerzita Tomáše Bati ve Zlíně',
             'name_en'             => '',
             'shortcut'            => 'UTB',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '34',
             'name'                => 'Žilinská univerzita v Žiline',
             'name_en'             => '',
             'shortcut'            => 'UNIZA',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '35',
             'name'                => 'Vysoká škola chemicko-technologická v Praze',
             'name_en'             => 'University of Chemistry and Technology, Prague',
             'shortcut'            => 'VŠCHT',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '36',
             'name'                => 'Vysoké učení technické v Brně',
             'name_en'             => 'Brno University of Technology',
             'shortcut'            => 'VUT',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '37',
             'name'                => 'VŠB – Technická univerzita Ostrava',
             'name_en'             => 'VSB - Technical University of Ostrava',
             'shortcut'            => 'VŠB',
             'country_id'          => '45',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '38',
             'name'                => 'Sliezska technická univerzita, Gliwice, Poľsko',
             'name_en'             => 'Silesian University of Technology, Gliwice, Poland',
             'shortcut'            => 'SUT',
             'country_id'          => '140',
             'created_at'          => now(),
             'updated_at'          => now()],

            ['id'                  => '39',
             'name'                => 'Univerzita veterinárskeho lekárstva a farmácie v Košiciach',
             'name_en'             => 'University of Veterinary Medicine and Pharmacy in Košice',
             'shortcut'            => 'UVLF',
             'country_id'          => '158',
             'created_at'          => now(),
             'updated_at'          => now()]
        ]);
    }
}
